### PR TITLE
Fix: Insecure dependencies

### PR DESCRIPTION
**Pull request by trasherdk**

### CODE REVIEW

**Comment by woodser** [comment]
y18n was updated by dependabot and I updated package-lock.json accordingly.  Now seeing 3 low severity vulnerabilities reported, which perhaps can be reduced further.

**Comment by trasherdk** [comment]
I could not find anywhere where babel-minify is used, and `npm uninstall babel-minify`
fixes the 2 warnings :)

**Comment by trasherdk** [comment]
On a side note regarding `babel-minify`
image

**Comment by woodser** [comment]
Fixed with https://github.com/woodser/monerowebwallet.com/commit/65b69475ec45037e0ea64328523b12e102a694c9.

**Pull request closed without merging**
